### ISSUE TITLE
Creation - Information Générale

### ISSUE THREAD

**Issue by Belleau6744** [Belleau6744/resume_generator#4]
# General Information Section
- [ ] As a student, I want to be able to fill in my general personal informations
- [ ] Student can Add/Edit known languages and proficiency level :  #5 

### Sections
- First Name
- Last Name
- Phone number
- Role Tile
- LinkedIn
- Email Address
- Languages

### Definition of done
- [ ] Can fill in the inputs for the required sections
- [ ] Can save/cancel the entries made
- [ ] Can edit previous entries
